# Generated by Django 5.2.7 on 2025-10-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_alter_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtDesicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.TextField(verbose_name='Шапка')),
                ('body', models.TextField(verbose_name='Тело')),
                ('decision', models.TextField(verbose_name='Решение')),
            ],
            options={
                'verbose_name': 'Судебное решение',
                'verbose_name_plural': 'Судебные решения',
            },
        ),
    ]
