# Generated by Django 5.2.7 on 2025-10-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_courtdesicion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourtDesicion',
            new_name='CourtDecision',
        ),
    ]
